flaskblog/gallery/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from flaskblog.models import Gallery
from wtforms.validators import DataRequired
from flask_uploads import UploadSet, IMAGES, configure_uploads


photos = UploadSet('photos', IMAGES)


class GalleryForm(FlaskForm):
    filepath = StringField('Filepath', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    caption = StringField('Caption', validators=[DataRequired()])
    submit = SubmitField('Upload to Gallery')

flaskblog/gallery/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db, basic_auth
from flask_basicauth import BasicAuth
from flaskblog.models import Gallery
from flaskblog.gallery.forms import GalleryForm
from flaskblog.users.utils import save_picture

gall = Blueprint('gall', __name__)

@gall.route("/gallery/new", methods=['GET', 'POST'])
@basic_auth.required
def new_image():
    form = GalleryForm()
    if form.validate_on_submit():
        gallerys = Gallery(filepath=form.filepath.data, location=form.location.data, caption=form.caption.data)
        db.session.add(gallerys)
        db.session.commit()
        flash('Your image has been uploaded!', 'success')
        return redirect(url_for('gall.gallery'))
    return render_template('create_gallery.html', title='New Image', form=form)

#new
gallery = ""

@gall.route("/gallery")
def gallery():
    gallery = Gallery.query.order_by(Gallery.location.desc())
    return render_template('gallery.html', images=images, title='Gallery', gallery=gallery)

# data
images = [
    {
        'filepath': 'static/photos/gallery/about_me.jpg',
        'location': 'Spokane, WA',
        'caption': 'Me in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/cathedralTwo.jpg',
        'location': 'Spokane, WA',
        'caption': 'Cathedral in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/christmasTexas.jpg',
        'location': 'Fort Worth, TX',
        'caption': 'Christmas Tree in Sundance Square'
    },
    {
        'filepath': 'static/photos/gallery/dunes.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach in Oregon'
    },
    {
        'filepath': 'static/photos/gallery/emergencyRoom.jpg',
        'location': 'Pasco, WA',
        'caption': 'Hospital in Pasco'
    },
    {
        'filepath': 'static/photos/gallery/FerrisWheelWashington.jpg',
        'location': 'Spokane, WA',
        'caption': 'Ferris Wheel in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/flower.jpg',
        'location': 'The Dalles, OR',
        'caption': 'A flower found at Mayer State Park'
    },
    {
        'filepath': 'static/photos/gallery/fourthOfJulySmoke.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Fireworks for the 4th of July in on the Ocean.'
    },
    {
        'filepath': 'static/photos/gallery/gardensOne.jpg',
        'location': 'Spokane, WA',
        'caption': 'Botanical Gardens at Manito Park'
    },
    {
        'filepath': 'static/photos/gallery/gardensTwo.jpg',
        'location': 'Spokane, WA',
        'caption': 'Botanical Gardens at Manito Park'
    },
    {
        'filepath': 'static/photos/gallery/home_page2.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'River along campsite in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/lake.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Sunset at park in Kennewick, WA'
    },
    {
        'filepath': 'static/photos/gallery/landing_page.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach in Depoe Bay, OR'
    },
    {
        'filepath': 'static/photos/gallery/me_at_beach.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Me on beach in Depoe Bay, OR'
    },
    {
        'filepath': 'static/photos/gallery/meGumWall.jpg',
        'location': 'Seattle, WA',
        'caption': 'Me at the Gum Wall in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/meowtropolitan.jpg',
        'location': 'Seattle, WA',
        'caption': 'Seattle Meowtropolitan'
    },
    {
        'filepath': 'static/photos/gallery/middleOfNowhereLake.jpg',
        'location': 'Unknown',
        'caption': 'Middle of Nowhere Lake'
    },
    {
        'filepath': 'static/photos/gallery/oceanAgain.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Ocean in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/oceanYetAgain.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Ocean in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/oneTree.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Tree at a park in Kennewick'
    },
    {
        'filepath': 'static/photos/gallery/oregonHotel.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'View from hotel on Oreogn coast'
    },
    {
        'filepath': 'static/photos/gallery/oregonHotelTwo.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Hotel on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/OregonOutlookSign.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Outlook sign at hotel on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/pathGreen.jpg',
        'location': 'Spokane, WA',
        'caption': 'A path at River Front Park'
    },
    {
        'filepath': 'static/photos/gallery/piano.jpg',
        'location': 'Spokane, WA',
        'caption': 'Inside the cathedral in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/pierL.jpg',
        'location': 'Leavenworth, WA',
        'caption': 'The river in Leavenworth'
    },
    {
        'filepath': 'static/photos/gallery/publicMarket.jpg',
        'location': 'Seattle, WA',
        'caption': 'Public Market in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/riverTwo.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Columbia River in Kennewick'
    },
    {
        'filepath': 'static/photos/gallery/rocksAndOcean.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/seattle.jpg',
        'location': 'Seattle, WA',
        'caption': 'Street view in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/spaceNeedle.jpg',
        'location': 'Seattle, WA',
        'caption': 'The Space Needle in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/steph.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'My anniversary with my girlfriend on the Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/sunset_me.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Me at a park in Kennewick watching the sunset'
    },
    {
        'filepath': 'static/photos/gallery/treeOutlook.jpg',
        'location': 'Newport, OR',
        'caption': 'Devils Punch Bowl outlook on Oregon Coast'
    },
    {
        'filepath': 'static/photos/gallery/trees.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Campground on the Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/view.jpg',
        'location': 'Fort Worth, TX',
        'caption': 'View from apartment overlooking the river in Texas'
    },
    {
        'filepath': 'static/photos/gallery/vines.jpg',
        'location': 'Seattle, WA',
        'caption': 'City center in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/washingtonWaterPower.jpg',
        'location': 'Spokane, WA',
        'caption': 'Washington Water Power in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/waves.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach on the Oregon coast'
    }
]

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)



blog=" "
gallery=" "

@main.route("/")
def index():
    return render_template('index.html', title="Home")

@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    per_page = 5
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page, per_page)
    return render_template('blog.html', posts=posts, title="Blog", blog=blog)

@main.route("/about")
def about():
    return render_template('about.html', title='About', about=about)

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.blog'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout", methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('main.blog'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

# enter email to request a password reset
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

# reset password with token
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block about %}
<div class="text-white">
  <header class="header">
    <div>
      <p class="header-intro">Hi, I'm</p>
      <h1 class="header-name">Jason</h1>
    </div>
  </header>

  <section class="about">
    <h2>| Introduction |</h2>
    <br>
    <p>Hi, I'm an aspiring remote freelance Python Developer currently based near Los Angeles, California.</p>
    <br>
    <p>I received my BS of Computer Science from Jackson State University in December 2017. I have worked at Lockheed Martin as a Software Engineer from graduation until present.</p>
  </section>

  <section class="passion">
    <h2>| Passions |</h2>
    <br>
    <p>Development: Programming for me is the ability to take something in my imagination and make it real.</p>
    <br>
    <p>Photography: Photography for me is the ability to take a moment in time and immortalize it.</p>
    <br>
    <p>Travel: Travel for me is the ability to see the world through someone else. </p>
  </section>

  <section class="contact">
    <h2>| Contact |</h2>
    <br>
    <p>If you are interested in talking to me about a project you would like me to work on for you, or
      if you have any questions in general. Please feel free to contact me at the email below. </p>
    <br>
    <p>Email: jasondreams0513@gmail.com</p>
  </section>

  <footer class="footer">
    <ul class="social">
      <li><a href="https://github.com/JsonTyler" target="_blank">Github</li>
      <li><a href="https://www.linkedin.com/in/jason-bruno/" target="=_blank">LinkedIn</li>
      <li><a href="https://www.youtube.com/" target="_blank">Youtube</li>
    </ul>
  </footer>
</div>
{% endblock about %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block account %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading text-light">{{ current_user.username }}</h2>
        <p class="text-secondary text-light">{{ current_user.email }}</p>
      </div>
    </div>
    <div class="content-section text-light">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
  </div>
{% endblock account %}

flaskblog/templates/blog.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section-main bg-light">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">

              <span class="icon ">
                <i class="fas fa-user"></i>
              </span>
              <a class="mr-2" href="{{ url_for('main.about') }}">{{ post.author.username }}</a>

              <span class="icon ">
                <i class="fas fa-calendar"></i>
              </span>
              <a class="mr-2 text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</a>

              <span class="icon ">
                <i class="fas fa-tags"></i>
              </span>
              <a class="mr-2 text-muted">{{ post.tags }}</a>

            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <img src="{{ post.image }}" width="100%" height=auto>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4 bg-light text-dark" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4 bg-light text-dark" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
      <a class="text-white">...</a>
      {% endif %}
    {% endfor %}
{% endblock content %}

{% block sidebar %}
<div class="content-section-sidebar bg-dark">
  <h3 class="text-light">Blog Topics</h3>
  <h6 class='text-muted bg-dark'>Want to be notified when there's a new post?</h6>
  <h6 class='text-muted bg-dark'>Sign up <a href="{{ url_for('users.register')}}">Here</a>.</h6>
    <ul class="list-group">
      <li class="list-group-item list-group-item-light">Latest Posts</li>
      <li class="list-group-item list-group-item-light">Announcements</li>
      <li class="list-group-item list-group-item-light">Calendars</li>
      <li class="list-group-item list-group-item-light">etc</li>
    </ul>

</div>
{% endblock sidebar %}

flaskblog/templates/create_gallery.html
{% extends "layout.html" %}
{% block new_gallery %}
<div class="content-section text-light">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Image</legend>
            <div class="form-group">
                {{ form.filepath.label(class="form-control-label") }}
                {% if form.filepath.errors %}
                    {{ form.filepath(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.filepath.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.filepath(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.location.label(class="form-control-label") }}
                {% if form.location.errors %}
                    {{ form.location(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.location.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.location(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.caption.label(class="form-control-label") }}
                {% if form.caption.errors %}
                    {{ form.caption(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.caption.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.caption(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock new_gallery %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block post %}
<div class="content-section text-light">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Post</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.tags.label(class="form-control-label") }}
                {% if form.tags.errors %}
                    {{ form.tags(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tags.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.tags(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock post %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js">
    <script type="text/javascript" src="https://kit.fontawesome.com/c035ad1537.js"></script>
    {% if title %}
        <title>JsonBytes - {{ title }}</title>
    {% else %}
        <title>JsonBytes</title>
    {% endif %}
</head>
<body class="bg-dark">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark border-bottom border-light rounded-bottom fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">{ JsonBytes };</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Blog</a>
              <a class="nav-item nav-link" href="{{ url_for('gall.gallery') }}">Gallery</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          {% block error %}{% endblock %}
          {% block login %}{% endblock %}
          {% block register %}{% endblock %}
          {% block account %}{% endblock %}
          {% block post %}{% endblock %}
          {% block request_reset %}{% endblock %}
          {% block reset_token %}{% endblock %}
          {% block new_gallery %}{% endblock %}
          {% block gall %}{% endblock %}
          {% block about %}{% endblock %}

          {% if blog %}
            {% block content %}{% endblock %}
          {% endif %}
          {% if gallery %}
            {% block gallery %}{% endblock %}
          {% endif %}
        </div>
        {% if blog %}
          {% block sidebar %}{% endblock %}
        {% endif %}
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function ($) {

				// delegate calls to data-toggle="demolightbox"
				$(document).delegate('*[data-toggle="demolightbox"]:not([data-gallery="navigateTo"])', 'click', function(event) {
					event.preventDefault();
					return $(this).ekkoLightbox({
					});
				});

			});
		</script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block login %}
    <div class="content-section text-light">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check text-light">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock login %}